import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ThemeProvider";

import Navbar from "@/components/navbar/Navbar";






const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            
            {/* SHADCN-UI ThemeProvider -> DARK-LIGHT MODE */}
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
                {/* OVERALL DIV */}
                <div className="min-h-screen">
                  <Navbar />

                  <main className="py-8">
                    {/* Container to center the content. */}
                    <div className="bg-blue-500 px-4 max-w-7xl mx-auto">
                      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">

                         <div className="hidden lg:block lg:col-span-3">
                            sidebar
                         </div>

                         <div className="lg:col-span-9">
                            {children}
                         </div>
                         
                      </div>
                    </div>

                  </main>

                </div>
                

            </ThemeProvider>
            
          </body>
        </html>
    </ClerkProvider>

  );
}
